[package]
name = "rust"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmcloud-component = "0.2.0"
wit-bindgen = { version = "0.36", features = ["default"] }
